In [1]:
import pandas as pd

In [3]:
DataFrame = pd.read_excel("energia.xlsx")

In [4]:
DataFrame

,ANO,RESIDENCIAL,COMERCIAL,RURAL,INDUSTRIA,IL.PÚBLICA,PODER PÚBLICO,SERV.PÚBLICO,CONS.PÓPRIO,TOTAL
0,2016,409031,392519,9031,1011380,40361,21712,53013,685,1937732
1,2015,414902,387789,9094,1069051,40483,22036,53820,681,1997855
2,2014,421161,376039,9478,1183620,41119,21297,52359,590,2105664
3,2013,409628,349071,9274,1314900,38346,20652,55244,439,2197553
4,2012,385308,322370,8745,1352134,37072,20259,56305,445,2182638
5,2011,365563,314433,8415,1375637,36955,18862,51776,390,2172031
6,2010,348705,317626,8271,1320658,35253,18186,47303,277,2096279
7,2009,331996,302885,7845,1166926,34086,17295,48048,335,1909415
8,2008,316535,297495,8340,1078747,36087,16755,51335,386,1805681
9,2007,293540,267798,10479,1040822,37817,15235,49823,370,1715883
10,2006,280214,232692,10225,957073,38312,14298,48276,368,1581457